enableColors: true

enableHyperlinks: true

enableInlineBuilds: true

enableProgressBars: true

enableTelemetry: false

enableTimers: true

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

progressBarStyle: hogsfather

yarnPath: .yarn/releases/yarn-3.4.1.cjs
